name: Build and upload to S3
on:
  push:
    branches:
      - main
jobs:
  build-jar:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Check Java version
        run: java --version
      - name: Tests
        run: ./gradlew test --info
      - name: Build
        run: ./gradlew clean build

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Update with your region

      - name: Upload JAR to S3
        run: aws s3 cp ${{ github.workspace }}/build/libs/BinanceLambda-1.0-SNAPSHOT.jar s3://s3stack-lambdajarbucketf659f486-rl5t5qovf5mx/

      - name: Update Lambda function
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1  # Replace with your AWS region
        run: |
          S3_LOCATION=$(cat s3_location.txt)
          aws lambda update-function-code \
            --function-name LambdaStack-CryptoLambda774C47DC-m387DdUOPLzu \
            --s3-bucket s3stack-lambdajarbucketf659f486-rl5t5qovf5mx \
            --s3-key BinanceLambda-1.0-SNAPSHOT.jar