name: Build and upload to S3
on:
  push:
    branches:
      - main
jobs:
  integration-tests:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Check Java version
        run: java --version
      - name: Build
        run: ./gradlew clean build